### ISSUE TITLE
How do I change the default colors?

### ISSUE THREAD

**Issue by evansbusobozi** [updivision/material-dashboard-laravel#22]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I want to change the orange color of the active side-bar link as well as the purple color on the card-headers.

# Current Behavior

I tried changing the color variables within the _variables.scss, as well as the hex codes in material-dashboard.css without any success.

**Comment by groovemen** [comment]
Hello @Evanzsnr,

Thank you for using our products, here is what you have to do to make the expected changes:

- to change the card-header of the cards (e.g. purple color) please go to `assets/scss/material-dashboard/_cards.scss` at **line 164** and replace the variables with your colors, or variables:
`background: linear-gradient(60deg, $purple-400, $purple-600);`

- in order to have for the sidebar the active color to be orange, you have to change the **data-color="rose"** from _sidebar_ to **data-color="orange"**. 

Don't forget to recompile the SASS after you make the changes.
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
